version: '2.4'

services:
  uwsgi:
    image: mcd_ms
    container_name: mcd_ms
    build: src/.
    restart: unless-stopped
    environment:
      FLASK_ENV: "development"
      PORT: "5000"
    ports:
      - "0.0.0.0:5000:5000"
    cpus: 0
